# Extra autostart processes
# exec-once = uwsm-app -- my-service

$terminal = uwsm-app -- xdg-terminal-exec
$browser = omarchy-launch-browser

exec-once = dropbox-cli start
exec-once = [workspace 9 silent] $terminal -- zillacore server
exec-once = [workspace 9 silent] $terminal -- ngrok http 4567 --url https://unsuppositional-subaerially-bennie.ngrok-free.dev
exec-once = [workspace 5 silent] uwsm-app -- discord

