# Extra env variables
# env = MY_GLOBAL_ENV,setting

# NVIDIA environment variables
# env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,radeonsi
# env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# Try to unset this to see if it fixes some games that use Proton
env = SDL_VIDEODRIVER,
